### ISSUE TITLE
BadNotSupported errors and cannot publish if setpublishing mode is set to true

### ISSUE THREAD

**Issue by designncode7** [Azure/iot-edge-opc-publisher#137]
We are using OPC Publisher to publish to IoT Hub.  This is our command line configuration in VS:
opcuadevice2  --deviceconnectionstring="HostName=opcuahub2018Jun27.azure-devices.net;DeviceId=opcuadevice2;SharedAccessKey=qDa7X+EWj6mZUZef4Cresi0lK88Gg7m04c=" --pf="C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\publishednodes.json" --tc="C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\telemetryconfiguration.json" --vc=true --noshutdown=true --ih=Http1 --si=20 --oi=20000 --op=20000 --fd=true

Errors occur when the publisher is run.  Please see the errors below (BadNotSupported).  
If this line is commented out in OpcSession.cs, then there are errors but the publisher does publish to IOT Hub.
line 840: opcSubscription.OpcUaClientSubscription.SetPublishingMode(true);

We are using the latest code.

>> Any ideas on what is causing this?

Errors when NO line is commented out:
[16:08:58 INF] Current directory is: C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\bin\Debug\netcoreapp2.1
[16:08:59 INF] Log file is: tssstrl-publisher.log
[16:08:59 INF] Log level is: info
[16:08:59 INF] Publisher is starting up...
[16:08:59 INF] Application Certificate store type is: X509Store
[16:08:59 INF] Application Certificate store path is: CurrentUser\UA_MachineDefault
[16:08:59 INF] Application Certificate subject name is: opcuadevice2
[16:08:59 INF] Application certificate found in Application Certificate Store
[16:08:59 INF] Application certificate is for Application URI 'urn:tssstrl:opcuadevice2:microsoft:', Application 'opcuadevice2 and has Subject 'opcuadevice2'
[16:08:59 INF] Trusted Issuer store type is: Directory
[16:08:59 INF] Trusted Issuer Certificate store path is: CertificateStores/issuers
[16:08:59 INF] Trusted Peer Certificate store type is: Directory
[16:08:59 INF] Trusted Peer Certificate store path is: CertificateStores/trusted
[16:08:59 INF] Rejected certificate store type is: Directory
[16:08:59 INF] Rejected Certificate store path is: CertificateStores/rejected
[16:08:59 INF] Rejection of SHA1 signed certificates is disabled
[16:08:59 INF] Minimum certificate key size set to 1024
[16:08:59 INF] Adding publisher certificate to trusted peer store. StorePath=CertificateStores/trusted
[16:08:59 ERR] Can not add publisher certificate to trusted peer store. StorePath=CertificateStores/trusted
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcStackConfiguration.ConfigureAsync() in C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\OpcStackConfiguration.cs:line 223
[16:08:59 INF] OperationTimeout set to 120000
[16:08:59 INF] Publisher server base address: opc.tcp://tssstrl:62222/UA/Publisher
[16:08:59 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[16:08:59 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[16:08:59 INF] opcstacktracemask set to: 0x0
[16:08:59 INF] There is no site configured.
[16:08:59 INF] Publisher configured to not auto trust server certificates. When connecting to servers, you need to manually copy the rejected server certs to the trusted store to trust them.
[16:08:59 INF] Starting server on endpoint opc.tcp://tssstrl:62222/UA/Publisher ...
[16:09:01 INF] Server started.
[16:09:01 INF] Attempting to load telemetry configuration file from: C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\telemetryconfiguration.json
[16:09:01 INF] The name of the configuration file for published nodes is: C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\publishednodes.json
[16:09:01 INF] Attemtping to load node configuration from: C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\publishednodes.json
[16:09:01 INF] Loaded 1 config file entry/entries.
[16:09:01 INF] There are 1 nodes to publish.
[16:09:01 INF] IoT Hub owner connection string not passed as argument.
[16:09:01 INF] IoTHub device cert store type is: X509Store
[16:09:01 INF] IoTHub device cert path is: My
[16:09:01 INF] IoT Hub owner connection string not specified. Assume device connection string already in cert store or passed in via command line option.
[16:09:01 INF] Adding device connectionstring to secure store.
[16:09:03 INF] Attempting to read device connection string from cert store using subject name: opcuadevice2
[16:09:03 INF] IoTCentral mode: False
[16:09:03 INF] Message processing and hub communication configured with a send interval of 20 sec and a message buffer size of 262144 bytes.
[16:09:03 INF] Creating task process and batch monitored item data updates...
[16:09:03 INF]
[16:09:03 INF]
[16:09:03 INF] Publisher is running infinite...
[16:09:03 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.155.25:9998/freeopcua/server'.
[16:09:05 ERR] Session creation to endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' failed 1 time(s). Please verify if server is up and Publisher configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\OpcSession.cs:line 580
[16:09:15 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'.
[16:09:16 ERR] Session creation to endpoint 'opc.tcp://192.168.155.25:9998/freeopcua/server' failed 2 time(s). Please verify if server is up and Publisher configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\OpcSession.cs:line 580
[16:09:27 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.155.25:9998/freeopcua/server'.
[16:09:27 INF] Create unsecured session for endpoint URI 'opc.tcp://192.168.166.25:9998/freeopcua/server' with timeout of 30000 ms.
[16:09:27 INF] Session successfully created with Id i=12.
[16:09:27 INF] The session to endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' has 3 entries in its namespace array:
[16:09:27 INF] Namespace index 0: http://opcfoundation.org/UA/
[16:09:27 INF] Namespace index 1: urn:freeopcua:python:server
[16:09:27 INF] Namespace index 2: http://example.proof.com
[16:09:27 INF] The server on endpoint 'opc.tcp://192.168.155.25:9998/freeopcua/server' supports a minimal sampling interval of 0 ms.
[16:09:27 INF] Created subscription with id 80 on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'
[16:09:27 INF] Create subscription on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' requested OPC publishing interval is 20000 ms. (revised: 20000 ms)
[16:09:27 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:09:27 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.155.25:9998/freeopcua/server'. Continue.
[16:09:27 ERR] Error in MonitorNodes.
Opc.Ua.ServiceResultException: BadNotImplemented
   at Opc.Ua.ClientBase.ValidateResponse(ResponseHeader header)
   at Opc.Ua.SessionClient.SetPublishingMode(RequestHeader requestHeader, Boolean publishingEnabled, UInt32Collection subscriptionIds, StatusCodeCollection& results, DiagnosticInfoCollection& diagnosticInfos)
   at Opc.Ua.Client.Subscription.SetPublishingMode(Boolean enabled)
   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in C:\Users\G.H\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\OpcSession.cs:line 841
[

Errors if the line 840 in OpcSession.CS is commented out:
opcSubscription.OpcUaClientSubscription.SetPublishingMode(true);

[16:24:41 INF] Current directory is: C:\Users\Ghassan.Hariz\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\bin\Debug\netcoreapp2.1
[16:24:41 INF] Log file is: tssstrl916-publisher.log
[16:24:41 INF] Log level is: info
[16:24:41 INF] Publisher is starting up...
[16:24:41 INF] Application Certificate store type is: X509Store
[16:24:41 INF] Application Certificate store path is: CurrentUser\UA_MachineDefault
[16:24:41 INF] Application Certificate subject name is: opcuadevice2
[16:24:41 INF] Application certificate found in Application Certificate Store
[16:24:41 INF] Application certificate is for Application URI 'urn:tssstrl916:opcuadevice2:microsoft:', Application 'opcuadevice2 and has Subject 'opcuadevice2'
[16:24:41 INF] Trusted Issuer store type is: Directory
[16:24:41 INF] Trusted Issuer Certificate store path is: CertificateStores/issuers
[16:24:41 INF] Trusted Peer Certificate store type is: Directory
[16:24:41 INF] Trusted Peer Certificate store path is: CertificateStores/trusted
[16:24:41 INF] Rejected certificate store type is: Directory
[16:24:41 INF] Rejected Certificate store path is: CertificateStores/rejected
[16:24:41 INF] Rejection of SHA1 signed certificates is disabled
[16:24:41 INF] Minimum certificate key size set to 1024
[16:24:42 INF] Adding publisher certificate to trusted peer store. StorePath=CertificateStores/trusted
[16:24:42 ERR] Can not add publisher certificate to trusted peer store. StorePath=CertificateStores/trusted
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcStackConfiguration.ConfigureAsync() in C:\Users\Ghassan.Hariz\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\OpcStackConfiguration.cs:line 223
[16:24:42 INF] OperationTimeout set to 120000
[16:24:42 INF] Publisher server base address: opc.tcp://tssstrl916:62222/UA/Publisher
[16:24:42 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[16:24:42 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[16:24:42 INF] opcstacktracemask set to: 0x0
[16:24:42 INF] There is no site configured.
[16:24:42 INF] Publisher configured to not auto trust server certificates. When connecting to servers, you need to manually copy the rejected server certs to the trusted store to trust them.
[16:24:42 INF] Starting server on endpoint opc.tcp://tssstrl916:62222/UA/Publisher ...
[16:24:43 INF] Server started.
[16:24:43 INF] Attempting to load telemetry configuration file from: C:\Users\Ghassan.Hariz\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\telemetryconfiguration.json
[16:24:44 INF] The name of the configuration file for published nodes is: C:\Users\Ghassan.Hariz\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\publishednodes.json
[16:24:44 INF] Attemtping to load node configuration from: C:\Users\Ghassan.Hariz\Documents\_IOT\IOT Dev\OPCUAPublisher\OPCUAPublisher2018Jul22\opcpublisher\publishednodes.json
[16:24:44 INF] Loaded 1 config file entry/entries.
[16:24:44 INF] There are 1 nodes to publish.
[16:24:44 INF] IoT Hub owner connection string not passed as argument.
[16:24:44 INF] IoTHub device cert store type is: X509Store
[16:24:44 INF] IoTHub device cert path is: My
[16:24:44 INF] IoT Hub owner connection string not specified. Assume device connection string already in cert store or passed in via command line option.
[16:24:44 INF] Adding device connectionstring to secure store.
[16:24:44 INF] Attempting to read device connection string from cert store using subject name: opcuadevice2
[16:24:44 INF] IoTCentral mode: False
[16:24:45 INF] Message processing and hub communication configured with a send interval of 20 sec and a message buffer size of 262144 bytes.
[16:24:45 INF] Creating task process and batch monitored item data updates...
[16:24:45 INF]
[16:24:45 INF]
[16:24:45 INF] Publisher is running infinite...
[16:24:45 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'.
[16:24:46 INF] Create unsecured session for endpoint URI 'opc.tcp://192.168.166.25:9998/freeopcua/server' with timeout of 10000 ms.
[16:24:46 INF] Session successfully created with Id i=14.
[16:24:46 INF] The session to endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' has 3 entries in its namespace array:
[16:24:46 INF] Namespace index 0: http://opcfoundation.org/UA/
[16:24:46 INF] Namespace index 1: urn:freeopcua:python:server
[16:24:46 INF] Namespace index 2: http://example.proof.com
[16:24:46 INF] The server on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' supports a minimal sampling interval of 0 ms.
[16:24:46 INF] Created subscription with id 82 on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'
[16:24:46 INF] Create subscription on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' requested OPC publishing interval is 20000 ms. (revised: 20000 ms)
[16:24:46 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:24:46 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:24:46 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 159 msec. Now monitoring 0 items in subscription with id '82'.
[16:24:56 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:24:56 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:24:57 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 149 msec. Now monitoring 0 items in subscription with id '82'.
[16:25:07 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:25:07 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:25:07 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 218 msec. Now monitoring 0 items in subscription with id '82'.
[16:25:17 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:25:17 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:25:17 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 194 msec. Now monitoring 0 items in subscription with id '82'.
[16:25:27 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:25:27 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:25:27 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 179 msec. Now monitoring 0 items in subscription with id '82'.
[16:25:37 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:25:37 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:25:37 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 181 msec. Now monitoring 0 items in subscription with id '82'.
[16:25:47 INF] Start monitoring items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Currently monitoring 0 items.
[16:25:48 ERR] Unhandled OPC UA ServiceResultException 'BadNotImplemented' when monitoring node '2' on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server'. Continue.
[16:25:48 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.166.25:9998/freeopcua/server' took 203 msec. Now monitoring 0 items in subscription with id '82'.

**Comment by hansgschossmann** [comment]
@designncode7  which OPC UA Server are you using. seems that there is somthing missing in it's implementation.

PS: i am OOF next three weeks, so there will be some delay in follow-up.

**Comment by hansgschossmann** [comment]
No answer for a while. Closing for now. Pls reopen if needed.
