### ISSUE TITLE
OPC simulator doesn't work with iotedge agent 1.0.1

### ISSUE THREAD

**Issue by bdewaele** [Azure/iot-edge-opc-publisher#154]
We're currently testing the opc publisher in combination with iotedge agent 1.0.1.
We needed to install and test the 1.0.1 version for proxy issues.  We're happy that his seem to be solved but now we're facing an issue with the OPC publisher.  We tested with the latest OPC publisher version.

Is this a known issue ? 

[11:12:12 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://10.17.89.29:443/OPCUA/SimulationServer'.
[11:12:12 ERR] Session creation to endpoint 'opc.tcp://10.17.89.29:443/OPCUA/SimulationServer' failed 11 time(s). Please verify if server is up and Publisher configuration
is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: Error received from remote host: Bad_TcpEndpointUrlInvalid (code=0x80830000, description="The Server does no
t recognize the QueryString specified.")
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionColl
ection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcpublisher/OpcSession.cs:line 605

**Comment by hansgschossmann** [comment]
The issue you are facing is most likely not related to IoT Edge versions. Can you please retry with the latest version or at least 2.2.0-preview001? Please reopen the issue if you still see errors.
