### ISSUE TITLE
Amqp does not work with IoTEdge

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iot-edge-opc-publisher#189]
I'm using OPC Publisher (2.3.1) as IoTEdge module. In the create options I defined the following command-line options:
```
"Cmd": [
                  "publisher",
                  "--pf=./pn.json",
                  "--tc=./telemetryConfig.json",
                  "--di=60",
                  "--to",
                  "--aa",
                  "--si=0",
                  "--ms=0",
                  "--ih=Amqp_Tcp_Only"
                ],
```
I defined to use the Amqp Protocoll (which is also used by all my other modules).
But OpcPublisher is connecting using the MQTT-Protocoll.

In the logging output of the publisher module I found the following line:
_When running as IoTEdge module Mqtt_Tcp_Only is enforced._
Why is that?

**Comment by sebader** [comment]
Fixed in https://github.com/Azure/iot-edge-opc-publisher/pull/191

**Comment by BewaControl-ReneDivossen** [comment]
@sebader 
Will this be a new release (2.3.2) ? Will there be a docker image for that?

**Comment by sebader** [comment]
I'll let @hansgschossmann comment on this but yes, I expect there will be a new release once the PR is merged

**Comment by BewaControl-ReneDivossen** [comment]
@sebader 
Thank's a lot for the quick reaction.
@hansgschossmann : It would be great to have a new release soon using the device sdk 1.19.0 and allowing to use AMQP with IotEdge.  This would hopefully allow for lossless and automatic recovery after an EdgeHub crash (which unfortunately right now seems to be inevitable because edgehub consumes more and more memory with time and sooner or later will crash)

**Comment by BewaControl-ReneDivossen** [comment]
@hansgschossmann I referenced opc-publisher:latest and I'm using Amqp as the only protocol now. It's running but automatic recovery does not work as expected. If I kill the edgeHub module using "docker stop" everything will recover nicely but if I kill the publisher module using "docker stop" it will not send messages anymore after coming up running again.

**Comment by hansgschossmann** [comment]
Can you share the log output of publisher?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by BewaControl-ReneDivossen** [comment]
@hansgschossmann Here comes the log output (Starting with the Publisher running and sending messages.  Then the Publisher docker image has been stopped and after recovering does not send messages anymore.  Then EdgeHub docker image has been stopped and after recovering Publisher send messages again):

`
[08:44:37 INF] ==========================================================================
[08:44:37 INF] OpcPublisher status @ 02/11/2019 08:44:37 (started @ 02/11/2019 08:38:18)
[08:44:37 INF] ---------------------------------
[08:44:37 INF] OPC sessions (configured/connected): 1/1
[08:44:37 INF] OPC subscriptions (configured/connected): 1/1
[08:44:37 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:44:37 INF] ---------------------------------
[08:44:37 INF] monitored items queue bounded capacity: 8192
[08:44:37 INF] monitored items queue current items: 0
[08:44:37 INF] monitored item notifications enqueued: 403
[08:44:37 INF] monitored item notifications enqueue failure: 0
[08:44:37 INF] ---------------------------------
[08:44:37 INF] messages sent to IoTHub: 402
[08:44:37 INF] last successful msg sent @: 02/11/2019 08:44:35
[08:44:37 INF] bytes sent to IoTHub: 23837
[08:44:37 INF] avg msg size: 59
[08:44:37 INF] msg send failures: 1
[08:44:37 INF] messages too large to sent to IoTHub: 0
[08:44:37 INF] times we missed send interval: 0
[08:44:37 INF] number of events: 403
[08:44:37 INF] ---------------------------------
[08:44:37 INF] current working set in MB: 76
[08:44:37 INF] --si setting: 0
[08:44:37 INF] --ms setting: 0
[08:44:37 INF] --ih setting: Amqp_Tcp_Only
[08:44:37 INF] ==========================================================================
[08:45:37 INF] ==========================================================================
[08:45:37 INF] OpcPublisher status @ 02/11/2019 08:45:37 (started @ 02/11/2019 08:38:18)
[08:45:37 INF] ---------------------------------
[08:45:37 INF] OPC sessions (configured/connected): 1/1
[08:45:37 INF] OPC subscriptions (configured/connected): 1/1
[08:45:37 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:45:37 INF] ---------------------------------
[08:45:37 INF] monitored items queue bounded capacity: 8192
[08:45:37 INF] monitored items queue current items: 1
[08:45:37 INF] monitored item notifications enqueued: 473
[08:45:37 INF] monitored item notifications enqueue failure: 0
[08:45:37 INF] ---------------------------------
[08:45:37 INF] messages sent to IoTHub: 470
[08:45:37 INF] last successful msg sent @: 02/11/2019 08:45:35
[08:45:37 INF] bytes sent to IoTHub: 27913
[08:45:37 INF] avg msg size: 59
[08:45:37 INF] msg send failures: 1
[08:45:37 INF] messages too large to sent to IoTHub: 0
[08:45:37 INF] times we missed send interval: 0
[08:45:37 INF] number of events: 472
[08:45:37 INF] ---------------------------------
[08:45:37 INF] current working set in MB: 76
[08:45:37 INF] --si setting: 0
[08:45:37 INF] --ms setting: 0
[08:45:37 INF] --ih setting: Amqp_Tcp_Only
[08:45:37 INF] ==========================================================================
IoTEdge detected.
[08:46:48 INF] Current directory is: /appdata
[08:46:48 INF] Log file is: publisher-publisher.log
[08:46:48 INF] Log level is: info
[08:46:48 INF] OPC Publisher V2.3.2+x starting up...
[08:46:48 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
[08:46:48 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
[08:46:48 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
[08:46:49 INF] opcstacktracemask set to: 0x0
[08:46:49 INF] OperationTimeout set to 120000
[08:46:49 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
[08:46:49 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[08:46:49 INF] Trusted Issuer store type is: Directory
[08:46:49 INF] Trusted Issuer Certificate store path is: pki/issuer
[08:46:49 INF] Trusted Peer Certificate store type is: Directory
[08:46:49 INF] Trusted Peer Certificate store path is: pki/trusted
[08:46:49 INF] Rejected certificate store type is: Directory
[08:46:49 INF] Rejected Certificate store path is: pki/rejected
[08:46:49 INF] Rejection of SHA1 signed certificates is disabled
[08:46:49 INF] Minimum certificate key size set to 1024
[08:46:49 INF] Application Certificate store type is: Directory
[08:46:49 INF] Application Certificate store path is: pki/own
[08:46:49 INF] Application Certificate subject name is: publisher
[08:46:49 WRN] WARNING: Automatically accepting certificates. This is a security risk.
[08:46:49 INF] Application certificate with thumbprint '58ADBC4966F4DD6351B205068DDF07504C3B88A8' found in the application certificate store.
[08:46:49 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
[08:46:49 INF] Adding server certificate to trusted peer store. StorePath=pki/trusted
[08:46:49 WRN] Can not add server certificate to trusted peer store. Maybe it is already there.
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcApplicationConfiguration.InitApplicationSecurityAsync() in /app/opcpublisher/OpcApplicationConfigurationSecurity.cs:line 241
[08:46:49 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[08:46:49 INF] Trusted issuer store contains 0 certs
[08:46:49 INF] Trusted issuer store has 0 CRLs.
[08:46:49 INF] Trusted peer store contains 1 certs
[08:46:49 INF] 01: Subject 'CN=publisher' (thumbprint: 58ADBC4966F4DD6351B205068DDF07504C3B88A8)
[08:46:49 INF] Trusted peer store has 0 CRLs.
[08:46:49 INF] Rejected certificate store contains 0 certs
[08:46:49 INF] There is no site configured.
[08:46:49 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
[08:46:57 INF] Server started.
[08:46:57 INF] Attempting to load telemetry configuration file from: ./telemetryConfig.json
[08:46:59 INF] The name of the configuration file for published nodes is: ./pn.json
[08:46:59 INF] Attemtping to load node configuration from: ./pn.json
[08:46:59 INF] Loaded 1 config file entry/entries.
[08:46:59 INF] There are 4 nodes to publish.
[08:46:59 INF] Protocol used for IoT EdgeHub communication is'Amqp_Tcp_Only'
[08:47:00 INF] IoTCentral mode: False
[08:47:04 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
[08:47:05 INF] Message processing and hub communication configured with a send interval of 0 sec and a message buffer size of 0 bytes.
[08:47:05 INF] Creating task process and batch monitored item data updates...
[08:47:05 INF]
[08:47:05 INF]
[08:47:05 INF] Publisher is running. Press CTRL-C to quit.
[08:47:06 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.88.10:4840'.
[08:47:07 INF] Create secured session for endpoint URI 'opc.tcp://192.168.88.10:4840' with timeout of 10000 ms.
[08:47:08 INF] Certificate 'O=Siemens, C=DE, CN=06-A1SPS/OPCUA-1-1' will be trusted, because of corresponding command line option.
[08:47:11 INF] Session successfully created with Id ns=1;i=1491323104.
[08:47:11 INF] The session to endpoint 'opc.tcp://192.168.88.10:4840/' has 4 entries in its namespace array:
[08:47:11 INF] Namespace index 0: http://opcfoundation.org/UA/
[08:47:11 INF] Namespace index 1: urn:SIMATIC.S7-1500.OPC-UA.Application:=06-A1 SPS
[08:47:11 INF] Namespace index 2: http://opcfoundation.org/UA/DI/
[08:47:11 INF] Namespace index 3: http://www.siemens.com/simatic-s7-opcua
[08:47:11 INF] Created subscription with id 1491322641 on endpoint 'opc.tcp://192.168.88.10:4840'
[08:47:11 INF] Create subscription on endpoint 'opc.tcp://192.168.88.10:4840' requested OPC publishing interval is 2000 ms. (revised: 2000 ms)
[08:47:11 INF] Start monitoring items on endpoint 'opc.tcp://192.168.88.10:4840'. Currently monitoring 0 items.
[08:47:11 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.88.10:4840' took 147 msec. Now monitoring 4 items in subscription with id '1491322641'.
[08:48:07 INF] ==========================================================================
[08:48:07 INF] OpcPublisher status @ 02/11/2019 08:48:07 (started @ 02/11/2019 08:46:47)
[08:48:07 INF] ---------------------------------
[08:48:07 INF] OPC sessions (configured/connected): 1/1
[08:48:07 INF] OPC subscriptions (configured/connected): 1/1
[08:48:07 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:48:07 INF] ---------------------------------
[08:48:07 INF] monitored items queue bounded capacity: 8192
[08:48:07 INF] monitored items queue current items: 62
[08:48:07 INF] monitored item notifications enqueued: 63
[08:48:07 INF] monitored item notifications enqueue failure: 0
[08:48:07 INF] ---------------------------------
[08:48:07 INF] messages sent to IoTHub: 0
[08:48:07 INF] last successful msg sent @: 01/01/0001 00:00:00
[08:48:07 INF] bytes sent to IoTHub: 59
[08:48:07 INF] avg msg size: 59
[08:48:07 INF] msg send failures: 0
[08:48:07 INF] messages too large to sent to IoTHub: 0
[08:48:07 INF] times we missed send interval: 0
[08:48:07 INF] number of events: 1
[08:48:07 INF] ---------------------------------
[08:48:07 INF] current working set in MB: 78
[08:48:07 INF] --si setting: 0
[08:48:07 INF] --ms setting: 0
[08:48:07 INF] --ih setting: Amqp_Tcp_Only
[08:48:07 INF] ==========================================================================
[08:49:07 INF] ==========================================================================
[08:49:07 INF] OpcPublisher status @ 02/11/2019 08:49:07 (started @ 02/11/2019 08:46:47)
[08:49:07 INF] ---------------------------------
[08:49:07 INF] OPC sessions (configured/connected): 1/1
[08:49:07 INF] OPC subscriptions (configured/connected): 1/1
[08:49:07 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:49:07 INF] ---------------------------------
[08:49:07 INF] monitored items queue bounded capacity: 8192
[08:49:07 INF] monitored items queue current items: 130
[08:49:07 INF] monitored item notifications enqueued: 131
[08:49:07 INF] monitored item notifications enqueue failure: 0
[08:49:07 INF] ---------------------------------
[08:49:07 INF] messages sent to IoTHub: 0
[08:49:07 INF] last successful msg sent @: 01/01/0001 00:00:00
[08:49:07 INF] bytes sent to IoTHub: 59
[08:49:07 INF] avg msg size: 59
[08:49:07 INF] msg send failures: 0
[08:49:07 INF] messages too large to sent to IoTHub: 0
[08:49:07 INF] times we missed send interval: 0
[08:49:07 INF] number of events: 1
[08:49:07 INF] ---------------------------------
[08:49:07 INF] current working set in MB: 78
[08:49:07 INF] --si setting: 0
[08:49:07 INF] --ms setting: 0
[08:49:07 INF] --ih setting: Amqp_Tcp_Only
[08:49:07 INF] ==========================================================================
[08:50:08 INF] ==========================================================================
[08:50:08 INF] OpcPublisher status @ 02/11/2019 08:50:08 (started @ 02/11/2019 08:46:47)
[08:50:08 INF] ---------------------------------
[08:50:08 INF] OPC sessions (configured/connected): 1/1
[08:50:08 INF] OPC subscriptions (configured/connected): 1/1
[08:50:08 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:50:08 INF] ---------------------------------
[08:50:08 INF] monitored items queue bounded capacity: 8192
[08:50:08 INF] monitored items queue current items: 200
[08:50:08 INF] monitored item notifications enqueued: 201
[08:50:08 INF] monitored item notifications enqueue failure: 0
[08:50:08 INF] ---------------------------------
[08:50:08 INF] messages sent to IoTHub: 0
[08:50:08 INF] last successful msg sent @: 01/01/0001 00:00:00
[08:50:08 INF] bytes sent to IoTHub: 59
[08:50:08 INF] avg msg size: 59
[08:50:08 INF] msg send failures: 0
[08:50:08 INF] messages too large to sent to IoTHub: 0
[08:50:08 INF] times we missed send interval: 0
[08:50:08 INF] number of events: 1
[08:50:08 INF] ---------------------------------
[08:50:08 INF] current working set in MB: 77
[08:50:08 INF] --si setting: 0
[08:50:08 INF] --ms setting: 0
[08:50:08 INF] --ih setting: Amqp_Tcp_Only
[08:50:08 INF] ==========================================================================
[08:50:15 ERR] Connection status changed to 'Disconnected_Retrying', reason 'Communication_Error'
[08:50:21 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
[08:51:08 INF] ==========================================================================
[08:51:08 INF] OpcPublisher status @ 02/11/2019 08:51:08 (started @ 02/11/2019 08:46:47)
[08:51:08 INF] ---------------------------------
[08:51:08 INF] OPC sessions (configured/connected): 1/1
[08:51:08 INF] OPC subscriptions (configured/connected): 1/1
[08:51:08 INF] OPC monitored items (configured/monitored/to remove): 4/4/0
[08:51:08 INF] ---------------------------------
[08:51:08 INF] monitored items queue bounded capacity: 8192
[08:51:08 INF] monitored items queue current items: 0
[08:51:08 INF] monitored item notifications enqueued: 269
[08:51:08 INF] monitored item notifications enqueue failure: 0
[08:51:08 INF] ---------------------------------
[08:51:08 INF] messages sent to IoTHub: 269
[08:51:08 INF] last successful msg sent @: 02/11/2019 08:51:07
[08:51:08 INF] bytes sent to IoTHub: 15911
[08:51:08 INF] avg msg size: 59
[08:51:08 INF] msg send failures: 0
[08:51:08 INF] messages too large to sent to IoTHub: 0
[08:51:08 INF] times we missed send interval: 0
[08:51:08 INF] number of events: 269
[08:51:08 INF] ---------------------------------
[08:51:08 INF] current working set in MB: 77
[08:51:08 INF] --si setting: 0
[08:51:08 INF] --ms setting: 0
[08:51:08 INF] --ih setting: Amqp_Tcp_Only
[08:51:08 INF] ==========================================================================`

**Comment by dmakarenko-connyun** [comment]
I built am image from the master branch and C2D message doesn't work with AMQP protocol (which is default now). Setting --ih=Mqtt_Tcp_Only fixes the problem.

**Comment by hansgschossmann** [comment]
I have looked into the Amqp issue today, but was not able to root cause the issue. If i revert Microsoft.Azure.Devices.Client back to 1.17.1 then C2D methods using Amqp starts working. Need to dig deeper.

**Comment by hansgschossmann** [comment]
@dmakarenko-connyun, @BewaControl-ReneDivossen: i have now pushed a fix which should enable Amqp as transport when running as IoT Edge module. If you have a chance, pls give it a try.

**Comment by dmakarenko-connyun** [comment]
@hansgschossmann Works for me. Thanks!

**Comment by BewaControl-ReneDivossen** [comment]
@hansgschossmann  My problem has also been solved with this fix.  

OpcPublisher recovers after all of the following:
- docker stop publisher
- docker stop edgeHub
- systemctl restart iotege
- reboot

Thank you very much for the quick response!

**Comment by hansgschossmann** [comment]
@BewaControl-ReneDivossen this is good to hear, i just have tested this as well and see no issues. i will kick of a tagged build today.

**Comment by hansgschossmann** [comment]
@BewaControl-ReneDivossen now the 2.3.3 release is available. Thanks for all your feedback and testing.

**Comment by dmakarenko-connyun** [comment]
@hansgschossmann today morning my publisher module was not responsive again. I was not able to send C2D messages for publisher but my own module connected using MQTT was very OK (both modules were running since yesterday).
Restarting the module didn't help, only after restarting the iotedge itself (`sudo systemctl restart iotedge`) the module was able to receive messages. 
Unfortunately I can't provide publisher logs and will investigate it further but using AMQP in production looks for not so reliable because of [this](https://github.com/Azure/azure-iot-sdk-csharp/issues/558).

**Comment by BewaControl-ReneDivossen** [comment]
@dmakarenko-connyun The last comments on the linked issue states that reconnection of modules works for AMQP but not for MQTT.  Did you try using AMQP for all your modules and disabling the MQTT head?

**Comment by dmakarenko-connyun** [comment]
@BewaControl-ReneDivossen sorry, my fault, looks like the similar issue for AMQP was [fixed](https://github.com/Azure/azure-iot-sdk-csharp/issues/571).
