### ISSUE TITLE
OPC Publisher does not start sending messages after IotEdge startup.

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iot-edge-opc-publisher#193]
Upon Powering On (or rebooting) the EdgeDevice, the OpcPublisher module is started along with the other iotEdge modules but it does not send any messages. The same is true if iotedge has been restarted using "systemctl restart iotedge".

To get OpcPublisher sending messages the edgeHub module has to be killed using "docker stop edgeHub".  Once edgeHub has restarted, the OpcPublisher starts sending messages.

We are using opc-publisher:latest set to AMQP.

This issue really is a show stopper for us.

There probably is a connection to this [issue](https://github.com/Azure/iot-edge-opc-publisher/issues/188).

Here comes the log:
`IoTEdge detected.
[15:55:49 INF] Current directory is: /appdata
[15:55:49 INF] Log file is: publisher-publisher.log
[15:55:49 INF] Log level is: info
[15:55:50 INF] OPC Publisher V2.3.2+x starting up...
[15:55:50 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
[15:55:50 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
[15:55:50 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
[15:55:50 INF] opcstacktracemask set to: 0x0
[15:55:50 INF] OperationTimeout set to 120000
[15:55:50 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
[15:55:50 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[15:55:50 INF] Trusted Issuer store type is: Directory
[15:55:50 INF] Trusted Issuer Certificate store path is: pki/issuer
[15:55:50 INF] Trusted Peer Certificate store type is: Directory
[15:55:50 INF] Trusted Peer Certificate store path is: pki/trusted
[15:55:50 INF] Rejected certificate store type is: Directory
[15:55:50 INF] Rejected Certificate store path is: pki/rejected
[15:55:50 INF] Rejection of SHA1 signed certificates is disabled
[15:55:50 INF] Minimum certificate key size set to 1024
[15:55:50 INF] Application Certificate store type is: Directory
[15:55:50 INF] Application Certificate store path is: pki/own
[15:55:50 INF] Application Certificate subject name is: publisher
[15:55:50 WRN] WARNING: Automatically accepting certificates. This is a security risk.
[15:55:51 INF] Application certificate with thumbprint '58ADBC4966F4DD6351B205068DDF07504C3B88A8' found in the application certificate store.
[15:55:51 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
[15:55:51 INF] Adding server certificate to trusted peer store. StorePath=pki/trusted
[15:55:51 WRN] Can not add server certificate to trusted peer store. Maybe it is already there.
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcApplicationConfiguration.InitApplicationSecurityAsync() in /app/opcpublisher/OpcApplicationConfigurationSecurity.cs:line 241
[15:55:51 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[15:55:51 INF] Trusted issuer store contains 0 certs
[15:55:51 INF] Trusted issuer store has 0 CRLs.
[15:55:51 INF] Trusted peer store contains 1 certs
[15:55:51 INF] 01: Subject 'CN=publisher' (thumbprint: 58ADBC4966F4DD6351B205068DDF07504C3B88A8)
[15:55:51 INF] Trusted peer store has 0 CRLs.
[15:55:51 INF] Rejected certificate store contains 0 certs
[15:55:51 INF] There is no site configured.
[15:55:51 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
[15:56:00 INF] Server started.
[15:56:00 INF] Attempting to load telemetry configuration file from: ./telemetryConfig.json
[15:56:02 INF] The name of the configuration file for published nodes is: ./pn.json
[15:56:02 INF] Attemtping to load node configuration from: ./pn.json
[15:56:02 INF] Loaded 1 config file entry/entries.
[15:56:02 INF] There are 16 nodes to publish.
[15:56:02 INF] Protocol used for IoT EdgeHub communication is'Amqp_Tcp_Only'
[15:56:04 INF] IoTCentral mode: False
[15:56:05 ERR] Connection status changed to 'Disconnected', reason 'Retry_Expired'
[15:59:12 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
[15:59:14 INF] Message processing and hub communication configured with a send interval of 0 sec and a message buffer size of 0 bytes.
[15:59:14 INF] Creating task process and batch monitored item data updates...
[15:59:14 INF]
[15:59:14 INF]
[15:59:14 INF] Publisher is running. Press CTRL-C to quit.
[15:59:14 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://192.168.88.10:4840'.
[15:59:15 INF] Create secured session for endpoint URI 'opc.tcp://192.168.88.10:4840' with timeout of 10000 ms.
[15:59:17 INF] Certificate 'O=Siemens, C=DE, CN=06-A1SPS/OPCUA-1-1' will be trusted, because of corresponding command line option.
[15:59:19 INF] Session successfully created with Id ns=1;i=2290423070.
[15:59:19 INF] The session to endpoint 'opc.tcp://192.168.88.10:4840/' has 4 entries in its namespace array:
[15:59:19 INF] Namespace index 0: http://opcfoundation.org/UA/
[15:59:19 INF] Namespace index 1: urn:SIMATIC.S7-1500.OPC-UA.Application:=06-A1 SPS
[15:59:19 INF] Namespace index 2: http://opcfoundation.org/UA/DI/
[15:59:19 INF] Namespace index 3: http://www.siemens.com/simatic-s7-opcua
[15:59:20 INF] Created subscription with id 2290422605 on endpoint 'opc.tcp://192.168.88.10:4840'
[15:59:20 INF] Create subscription on endpoint 'opc.tcp://192.168.88.10:4840' requested OPC publishing interval is 2000 ms. (revised: 2000 ms)
[15:59:20 INF] Start monitoring items on endpoint 'opc.tcp://192.168.88.10:4840'. Currently monitoring 0 items.
[15:59:20 INF] Done processing unmonitored items on endpoint 'opc.tcp://192.168.88.10:4840' took 922 msec. Now monitoring 16 items in subscription with id '2290422605'.
[16:00:15 INF] ==========================================================================
[16:00:15 INF] OpcPublisher status @ 02/12/2019 16:00:15 (started @ 02/12/2019 15:55:47)
[16:00:15 INF] ---------------------------------
[16:00:15 INF] OPC sessions (configured/connected): 1/1
[16:00:15 INF] OPC subscriptions (configured/connected): 1/1
[16:00:15 INF] OPC monitored items (configured/monitored/to remove): 16/16/0
[16:00:15 INF] ---------------------------------
[16:00:15 INF] monitored items queue bounded capacity: 8192
[16:00:15 INF] monitored items queue current items: 155
[16:00:15 INF] monitored item notifications enqueued: 156
[16:00:15 INF] monitored item notifications enqueue failure: 0
[16:00:15 INF] ---------------------------------
[16:00:15 INF] messages sent to IoTHub: 0
[16:00:15 INF] last successful msg sent @: 01/01/0001 00:00:00
[16:00:15 INF] bytes sent to IoTHub: 47
[16:00:15 INF] avg msg size: 47
[16:00:15 INF] msg send failures: 0
[16:00:15 INF] messages too large to sent to IoTHub: 0
[16:00:15 INF] times we missed send interval: 0
[16:00:15 INF] number of events: 1
[16:00:15 INF] ---------------------------------
[16:00:15 INF] current working set in MB: 75
[16:00:15 INF] --si setting: 0
[16:00:15 INF] --ms setting: 0
[16:00:15 INF] --ih setting: Amqp_Tcp_Only
[16:00:15 INF] ==========================================================================
[16:01:15 INF] ==========================================================================
[16:01:15 INF] OpcPublisher status @ 02/12/2019 16:01:15 (started @ 02/12/2019 15:55:47)
[16:01:15 INF] ---------------------------------
[16:01:15 INF] OPC sessions (configured/connected): 1/1
[16:01:15 INF] OPC subscriptions (configured/connected): 1/1
[16:01:15 INF] OPC monitored items (configured/monitored/to remove): 16/16/0
[16:01:15 INF] ---------------------------------
[16:01:15 INF] monitored items queue bounded capacity: 8192
[16:01:15 INF] monitored items queue current items: 320
[16:01:15 INF] monitored item notifications enqueued: 321
[16:01:15 INF] monitored item notifications enqueue failure: 0
[16:01:15 INF] ---------------------------------
[16:01:15 INF] messages sent to IoTHub: 0
[16:01:15 INF] last successful msg sent @: 01/01/0001 00:00:00
[16:01:15 INF] bytes sent to IoTHub: 47
[16:01:15 INF] avg msg size: 47
[16:01:15 INF] msg send failures: 0
[16:01:15 INF] messages too large to sent to IoTHub: 0
[16:01:15 INF] times we missed send interval: 0
[16:01:15 INF] number of events: 1
[16:01:15 INF] ---------------------------------
[16:01:15 INF] current working set in MB: 75
[16:01:15 INF] --si setting: 0
[16:01:15 INF] --ms setting: 0
[16:01:15 INF] --ih setting: Amqp_Tcp_Only
[16:01:15 INF] ==========================================================================
[16:02:15 INF] ==========================================================================
[16:02:15 INF] OpcPublisher status @ 02/12/2019 16:02:15 (started @ 02/12/2019 15:55:47)
[16:02:15 INF] ---------------------------------
[16:02:15 INF] OPC sessions (configured/connected): 1/1
[16:02:15 INF] OPC subscriptions (configured/connected): 1/1
[16:02:15 INF] OPC monitored items (configured/monitored/to remove): 16/16/0
[16:02:15 INF] ---------------------------------
[16:02:15 INF] monitored items queue bounded capacity: 8192
[16:02:15 INF] monitored items queue current items: 487
[16:02:15 INF] monitored item notifications enqueued: 488
[16:02:15 INF] monitored item notifications enqueue failure: 0
[16:02:15 INF] ---------------------------------
[16:02:15 INF] messages sent to IoTHub: 0
[16:02:15 INF] last successful msg sent @: 01/01/0001 00:00:00
[16:02:15 INF] bytes sent to IoTHub: 47
[16:02:15 INF] avg msg size: 47
[16:02:15 INF] msg send failures: 0
[16:02:15 INF] messages too large to sent to IoTHub: 0
[16:02:15 INF] times we missed send interval: 0
[16:02:15 INF] number of events: 1
[16:02:15 INF] ---------------------------------
[16:02:15 INF] current working set in MB: 75
[16:02:15 INF] --si setting: 0
[16:02:15 INF] --ms setting: 0
[16:02:15 INF] --ih setting: Amqp_Tcp_Only
[16:02:15 INF] ==========================================================================`

**Comment by BewaControl-ReneDivossen** [comment]
Fixed with this [commit](https://github.com/Azure/iot-edge-opc-publisher/commit/8f1d85f284bc9891b97eb7e683ad00ed3816072f)
