### ISSUE TITLE
Out of Memory Exception when loading large pn.json file

### ISSUE THREAD

**Issue by jmbrunskill** [Azure/iot-edge-opc-publisher#209]
Hi,

We are trying to load in an admitted very large published nodes configuration for our IoT Edge deployment.

It looks like the System.Text.StringBuilder is failing on startup with an out of memory exception...

```
[04:22:45 INF] Starting server on endpoint opc.tcp://opcpublisher:62222/UA/Publisher ...
[04:22:46 INF] Server started.
[04:22:46 INF] Using default telemetry configuration.
[04:22:46 INF] The name of the configuration file for published nodes is: ./pn.json
[04:22:46 INF] Attemtping to load node configuration from: ./pn.json
[04:22:49 FTL] Loading of the node configuration file failed. Does the file exist and has correct syntax? Exiting...
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at OpcPublisher.PublisherNodeConfiguration.ReadConfigAsync() in /app/opcpublisher/PublisherNodeConfiguration.cs:line 222
```

I don't think there is an actual host memory limit being hit, from a quick google it looks like StringBuilder can have issues with very large strings?

**Version Information**
```
Ubuntu 18.04
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
mcr.microsoft.com/iotedge/opc-publisher:2.3.2
```

**Comment by jmbrunskill** [comment]
I can confirm it does work ok with a 35MB file (165,000 nodes), I had a bug in my code that was causing a lot of duplicated configuration which explains why my file go so big. So this memory limit might not be a big issue for us after all. Seems like <100MB is ok for StringBuilder. We do expect to be working with very high node counts though > 200k so keen to identify any limits that might trip up us on moving towards that goal.
