### ISSUE TITLE
Could not find telemetry configuration file

### ISSUE THREAD

**Issue by terrymandin** [Azure/iot-edge-opc-publisher#218]
I am getting an error when I try to load a new telemetry format on Windows.

**Publisher Configuration:**

{
  "Hostname": "publisher",
  "Cmd": [
    "--pf=./pn.json",
    "--tc=./telemetryconfiguration.json",
    "--ll=verbose",
    "--aa"
  ],
  "HostConfig": {
    "Binds": [
      "C:\\iiotedge\\appdata"
    ],
    "ExtraHosts": [
      "ENBZW2POCDEKEP1:51.143.1.255"
    ]
  }
}

**PC Configuration:**

IoT Edge Version: iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Publisher Version: 2.3
OS: Microsoft Windows Version 1809 (OS Build 17763.379)

**Error:**

[08:39:44 INF] Attempting to load telemetry configuration file from: ./telemetryconfiguration.json
[08:39:44 FTL] Loading of the telemetry configuration file failed. Does the file exist and has correct syntax? Exiting...
System.IO.FileNotFoundException: Could not find file 'C:\appdata\telemetryconfiguration.json'.
File name: 'C:\appdata\telemetryconfiguration.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at OpcPublisher.PublisherTelemetryConfiguration.ReadConfigAsync() in C:\app\opcpublisher\PublisherTelemetryConfiguration.cs:line 521

Note that it is looking for the file in the wrong location.  It is looking in c:\appdata when it should be looking in c:\iiotedge\appdata.   I have placed the telemetryconfiguration.json file in both locations and get the same error.

**Comment by terrymandin** [comment]
I figured out my issue.  My binding was incorrect. it should be:

c:/iiotedge:c:/appdata

I will close now.

**Comment by terrymandin** [comment]
I figured out my issue. My binding was incorrect. it should be:

c:/iiotedge:c:/appdata
