### ISSUE TITLE
error message when publishing array of values

### ISSUE THREAD

**Issue by fijo1015** [Azure/iot-edge-opc-publisher#281]
Hi,

I have a subscription to a VariableNode, that consists a onedimensional array of values. In the following there is a code snippet:

> VariableNodeArrayOneDimension::VariableNodeArrayOneDimension(std::string nodeName,
	UA_Server *server,
	UA_NodeId ParentNodeId,
	UA_NodeId RefrenceNodeId,
	UA_QualifiedName browseName,
	UA_NodeId typeDefinition,
	UA_NodeId dataType)
	:m_NodeName(nodeName)
> {
> 	    m_VariableAttr					=	UA_VariableAttributes_default;
> 	m_VariableAttr.displayName		=	UA_LOCALIZEDTEXT_CONST("en-US", m_NodeName.c_str());
> 	m_VariableAttr.description		=	UA_LOCALIZEDTEXT_CONST("en-US", "");
> 	m_VariableAttr.accessLevel		=	UA_ACCESSLEVELMASK_READ | UA_ACCESSLEVELMASK_WRITE;
> 	m_VariableAttr.dataType			=	UA_NODEID_NUMERIC(0, UA_NS0ID_DOUBLE);
> 	m_VariableAttr.valueRank		=	UA_VALUERANK_ANY;
> 	m_VariableAttr.arrayDimensions	=	(UA_UInt32 *)UA_Array_new(2, &UA_TYPES[UA_TYPES_DOUBLE]);

> 	
> 	const unsigned int array_size = 2;
> 	
> 	UA_Double values[array_size];
> 	
> 	for (unsigned int i = 0; i < array_size; i++)
> 	{
> 		values[i] = (UA_Double)i;
> 	}
> 
> 	UA_Variant_setArray(&m_VariableAttr.value, values, array_size, &UA_TYPES[UA_TYPES_DOUBLE]);
> 	
> 	// 1-dimensional array
> 	UA_UInt32 myArrayDimensions[1]			= { array_size };
> 	m_VariableAttr.value.arrayDimensions		= myArrayDimensions;
> 	m_VariableAttr.value.arrayDimensionsSize	= 1;
> 	
> 	//Add Node to adress space
> 	UA_StatusCode retval = UA_Server_addVariableNode(	server,
> 														UA_NODEID_NUMERIC(1, NULL),		// new node id
> 														ParentNodeId,					// parent node
> 														RefrenceNodeId,					// reference type
> 														browseName,						// node browse name
> 														typeDefinition,					
> 														m_VariableAttr, NULL, NULL);
> }; 

The UAExpert shows this node attributes:

![Screenshot_ArrayNode](https://user-images.githubusercontent.com/73999251/100992929-09552780-3555-11eb-8800-6e76500afd06.png)

When I want to publish the array of value using OPC Publisher, I get the following error message:

> [09:33:58 ERR] Error processing monitored item notification 
> System.InvalidCastException: Unable to cast object of type 'Opc.Ua.Matrix' to type 'System.Double[]'.
>    at Opc.Ua.JsonEncoder.WriteVariantContents(Object value, TypeInfo typeInfo)
>    at Opc.Ua.JsonEncoder.WriteVariant(String fieldName, Variant value)
>    at Opc.Ua.JsonEncoder.WriteDataValue(String fieldName, DataValue value)
>    at OpcPublisher.OpcMonitoredItem.MonitoredItemNotificationEventHandler(MonitoredItem monitoredItem, MonitoredItemNotificationEventArgs e) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcMonitoredItem.cs:line 478 

Now I have two questions:
1. Is OPC Publisher able to publish an one- or multidimensional array of values?
2. If yes, can anybody tell me, what I did wrong? 

I would be grateful if somebody could help me.

Best regards
jo

**Comment by fijo1015** [comment]
It works ...
