### ISSUE TITLE
User is unable to connect from opc publisher to opcua server from aspentech. User Can connect to opcua server from generic client

### ISSUE THREAD

**Issue by daelsala** [Azure/iot-edge-opc-publisher#283]
Below is the Users JSON configurations along with the error received when attempting to connect:

JSON Config:
`json config

[
  {
    "EndpointUrl": "opc.tcp://PENPPRC23:63500/InfoPlus21/OpcUa/Server",
    "OpcAuthenticationMode": "UsernamePassword",
    "OpcAuthenticationUsername": "domain\\userID",
    "OpcAuthenticationPassword": "password",
    "UseSecurity": true,
    "OpcNodes": [
      {
        "Id": "ns=2;i=2186",
        "OpcSamplingInterval": 1000,
        "OpcPublishingInterval": 5000,
        "DisplayName": "hmddp"
      }
    ]
  }
]
`

Powershell Output:
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> docker -H npipe:////./pipe/iotedge_moby_engine logs -f OPCPublisher --tail 100
  # Ingress DataChanges (from OPC)     :              0
  # Ingress ValueChanges (from OPC)    :              0
  # Ingress BatchBlock buffer size     :              0
  # Encoding Block input/output size   :              0 | 0
  # Encoder Notifications processed    :              0
  # Encoder Notifications dropped      :              0
  # Encoder IoT Messages processed     :              0
  # Encoder avg Notifications/Message  :              0
  # Encoder avg IoT Message body size  :              0 (0%)
  # Encoder avg IoT Chunk (4 KB) usage :              0
  # Estimated IoT Chunks (4 KB) per day:              0
  # Outgress Batch Block buffer size   :              0
  # Outgress input buffer count        :              0
  # Outgress input buffer dropped      :              0
  # Outgress IoT message count         :              0
  # Connection retries                 :             36

[10:10:35 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:10:45 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:10:55 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:05 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:15 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:25 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.DataFlowProcessingEngine]
  DIAGNOSTICS INFORMATION for          : opc.tcp://PENPPRC23:63500/InfoPlus21/OpcUa/Server_8e2de58a172f45939359ae6dc072905aa4561010
  # Ingestion duration                 :    00:00:00:00 (dd:hh:mm:ss)
  # Ingress DataChanges (from OPC)     :              0
  # Ingress ValueChanges (from OPC)    :              0
  # Ingress BatchBlock buffer size     :              0
  # Encoding Block input/output size   :              0 | 0
  # Encoder Notifications processed    :              0
  # Encoder Notifications dropped      :              0
  # Encoder IoT Messages processed     :              0
  # Encoder avg Notifications/Message  :              0
  # Encoder avg IoT Message body size  :              0 (0%)
  # Encoder avg IoT Chunk (4 KB) usage :              0
  # Estimated IoT Chunks (4 KB) per day:              0
  # Outgress Batch Block buffer size   :              0
  # Outgress input buffer count        :              0
  # Outgress input buffer dropped      :              0
  # Outgress IoT message count         :              0
  # Connection retries                 :             42

[10:11:35 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:45 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:11:55 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:12:05 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:12:15 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:12:25 WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] Failed to create session '8e2de58a172f45939359ae6dc072905aa4561010' due to One or more errors occurred. (Error establishing a connection: BadNotConnected)
[10:12:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] File C:/appdata/pn.json has changed, reloading...
Unhandled exception. Microsoft.Azure.IIoT.Exceptions.SerializerException: Bad JSON escape sequence: \p. Path '[0].OpcAuthenticationUsername', line 5, position 39.
 ---> Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \p. Path '[0].OpcAuthenticationUsername', line 5, position 39.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(TextReader reader, Type objectType)
   at Microsoft.Azure.IIoT.Serializers.NewtonSoft.NewtonSoftJsonSerializer.Deserialize(ReadOnlyMemory`1 buffer, Type type) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Serializers.NewtonSoft\src\Default\NewtonSoftJsonSerializer.cs:line 76
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Serializers.NewtonSoft.NewtonSoftJsonSerializer.Deserialize(ReadOnlyMemory`1 buffer, Type type) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Serializers.NewtonSoft\src\Default\NewtonSoftJsonSerializer.cs:line 80
   at Microsoft.Azure.IIoT.Serializers.SerializerEx.Deserialize(ISerializer serializer, String str, Type type) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Abstractions\src\Serializers\Extensions\SerializerEx.cs:line 143
   at Microsoft.Azure.IIoT.Serializers.SerializerEx.Deserialize[T](ISerializer serializer, String json) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Abstractions\src\Serializers\Extensions\SerializerEx.cs:line 179
   at Microsoft.Azure.IIoT.Serializers.SerializerEx.Deserialize[T](ISerializer serializer, TextReader reader) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Abstractions\src\Serializers\Extensions\SerializerEx.cs:line 167
   at Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter.Read(TextReader publishedNodesFile, LegacyCliModel legacyCliModel) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Edge.Publisher\src\Storage\PublishedNodesJobConverter.cs:line 54
   at Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator.RefreshJobFromFile() in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Edge.Publisher\src\Engine\LegacyJobOrchestrator.cs:line 144
   at Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator._fileSystemWatcher_Changed(Object sender, FileSystemEventArgs e) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Edge.Publisher\src\Engine\LegacyJobOrchestrator.cs:line 124
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
[10:12:34 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.DataFlowProcessingEngine]
  DIAGNOSTICS INFORMATION for          : opc.tcp://PENPPRC23:63500/InfoPlus21/OpcUa/Server_8e2de58a172f45939359ae6dc072905aa4561010
  # Ingestion duration                 :    00:00:00:00 (dd:hh:mm:ss)
  # Ingress DataChanges (from OPC)     :              0
  # Ingress ValueChanges (from OPC)    :              0
  # Ingress BatchBlock buffer size     :              0
  # Encoding Block input/output size   :              0 | 0
  # Encoder Notifications processed    :              0
  # Encoder Notifications dropped      :              0
  # Encoder IoT Messages processed     :              0
  # Encoder avg Notifications/Message  :              0
  # Encoder avg IoT Message body size  :              0 (0%)
  # Encoder avg IoT Chunk (4 KB) usage :              0
  # Estimated IoT Chunks (4 KB) per day:              0
  # Outgress Batch Block buffer size   :              0
  # Outgress input buffer count        :              0
  # Outgress input buffer dropped      :              0
  # Outgress IoT message count         :              0
  # Connection retries                 :             48

PS C:\Windows\system32>

`

**Comment by daelsala** [comment]
@barnstee if you can please assist as soon as possible.

**Comment by koepalex** [comment]
The crash is caused by invalid escape sequence, please try `domain\\userID` for "OpcAuthenticationUsername". 
Can you verify if this works?

**Comment by daelsala** [comment]
> The crash is caused by invalid escape sequence, please try `"domain\\userID"` for "OpcAuthenticationUsername".
> Can you verify if this works?

@koepalex 
They can push the keys but don’t know how to confirm if it is working correctly.
Do they need to stop/restart the services.
Is there an output command I can run to provide feedback?

**Comment by koepalex** [comment]
Restart the publisher: `iotedge restart <publisher-module-name>`
Show the logs: `iotedge logs <publisher-module-name>`

**Comment by daelsala** [comment]
> Restart the publisher: `iotedge restart <publisher-module-name>`
> Show the logs: `iotedge logs <publisher-module-name>`

after customer tested the run:
PS C:\Windows\system32> net stop iotedge
...
The Azure IoT Edge Daemon service was stopped successfully.

PS C:\Windows\system32> net start iotedge
The Azure IoT Edge Daemon service is starting.
The Azure IoT Edge Daemon service was started successfully.

**Comment by daelsala** [comment]
[OPCTroubleshooting.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5680475/OPCTroubleshooting.txt)

Attached is the log output from cx

**Comment by daelsala** [comment]
> [OPCTroubleshooting.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5680475/OPCTroubleshooting.txt)
> 
> Attached is the log output from cx

Contains logs for edgeAgent and edgeHub

**Comment by daelsala** [comment]
Latest Logs after restarting attacehd below
[OPCTroubleShooting2.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5680579/OPCTroubleShooting2.txt)

**Comment by daelsala** [comment]
Attached are verbose logging files from cx
[OPCTroubleShooting3.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5681723/OPCTroubleShooting3.txt)
[OPCTroubleShooting4.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5681724/OPCTroubleShooting4.txt)

**Comment by koepalex** [comment]
`Failed to connect to opc.tcp://penpapp23.apm.ascend.com:63500/InfoPlus21/OpcUa/Server: Error establishing a connection: BadNotConnected - try again...` 

This indicates that the OPC Publisher is not able to connect to OPC UA Server, it is not related to security settings, otherwise there would be an `SecurityCheckFailed` in the log.

**Comment by koepalex** [comment]
How to check the connection to OPC UA server from iot edge host system: `Test-NetConnection -ComputerName "PENPPRC23" -Port 63500 -InformationLevel "Detailed"`

**Comment by koepalex** [comment]
How to check the connection to OPC UA server from insight OPC Publisher docker container:

`sudo docker exec -it -u root --privileged <publisher-module-name> bash`

```bash
# Install netcat if not available
sudo apt update
sudo apt install netcat
# Test TCP connection to address
nc -z -v PENPPRC23 63500
```

**Comment by daelsala** [comment]
Closing issue. Not a bug with OPC publisher, root cause was an unrelated connectivity issue
