### ISSUE TITLE
Error: Opc.Ua.ServiceResultException: Cannot access certificate private key

### ISSUE THREAD

**Issue by ksaye** [Azure/iot-edge-opc-publisher#302]
OPC Publisher Version:  2.7.206.36449
OS: Ubuntu 18.04
hostname of iotedge: home
Module URI:  mcr.microsoft.com/iotedge/opc-publisher:latest
Container Create Options:

```
{
    "Hostname": "publisher",
    "Cmd": [
        "publisher",
        "--pf=/appdata/publishednodes.json",
        "--aa",
        "--diagnosticsinterval=120",
        "--tm",
        "--lf=/appdata/publisher.log",
        "--ll=debug",
        "PkiRootPath=/appdata/pki",
        "ApplicationName=opcpublisher",
        "ApplicationCertificateSubjectName=CN=opcpublisher,O=device1,DC=home"
    ],
    "HostConfig": {
        "Binds": [
            "/iiotedge:/appdata",
            "/iiotedgecerts:/appdata/pki"
        ]
    }
}
```

Publishednodes.json:
```
[
  {
    "EndpointUrl": "opc.tcp://192.168.15.200:50000",
    "UseSecurity": true,
    "OpcNodes": [
      { "Id": "ns=2;s=SlowUInt1", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt2", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt3", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt4", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt5", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt6", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt7", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt8", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt9", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt10", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt11", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt12", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt13", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt14", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt15", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt16", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt17", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt18", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt19", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt20", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt21", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt22", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt23", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt24", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=SlowUInt25", "OpcPublishingInterval": 10000 },
      { "Id": "ns=2;s=FastUInt1" },
      { "Id": "ns=2;s=FastUInt2" },
      { "Id": "ns=2;s=FastUInt3" },
      { "Id": "ns=2;s=FastUInt4" },
      { "Id": "ns=2;s=FastUInt5" }
    ]
  }
]
```

Commands to create and copy the certificates:
```
openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -subj "/CN=opcpublisher/O=device1/DC=home" -keyout privateKey.key -out publicCert.crt
openssl pkcs12 -export -keypbe NONE -certpbe NONE -out privateKey.pfx -inkey privateKey.key -in publicCert.crt
# just hitting enter when asked for the private key
openssl x509 -outform der -in publicCert.crt -out publicCert.der

cp publicCert.der /iiotedgecerts/own/certs/
cp publicCert.der /iiotedgecerts/trusted/certs/
cp privateKey.pfx /iiotedgecerts/own/private/
```

Permissions on the private key:
```
root@home:~/blog# ls -all /iiotedgecerts/own/private/
total 12
drwxr-xr-x 2 root root 4096 Feb 23 15:42 .
drwxr-xr-x 4 root root 4096 Feb 18 16:55 ..
-rwxrwxrwx 1  777 root 2469 Feb 23 16:10 privateKey.pfx
```

Error message:
```
[22:12:16 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Connecting all clients to home using MqttOverTcp.
[22:12:16 INF Root] Starting module OpcPublisher version 2.7.206.36449.
[22:12:16 INF Root] Initiating prometheus at port 9702/metrics
[22:12:16 INF Root] Prometheus metric server started.
[22:12:16 DBG Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Starting Module Host...
[22:12:16 WRN Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Bypassing certificate validation for client.
[22:12:16 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Running in iotedge context.
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: IotHubConnectionString#63993496 .ctor IAuthenticationMethod is AuthenticationWithTokenRefresh: ModuleAuthenticationWithHsm#36936550
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set ITransportSettings[] = Microsoft.Azure.Devices.Client.ITransportSettings[1]
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set IotHubConnectionString = IotHubConnectionString#63993496
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set OnMethodCalledDelegate = OnMethodCalledDelegate#358618857
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set Action`1 = System.Action`1[Microsoft.Azure.Devices.Shared.TwinCollection]
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set ConnectionStatusChangesHandler = ConnectionStatusChangesHandler#362428870
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set OnReceiveEventMessageCalledDelegate = OnReceiveEventMessageCalledDelegate#396718990
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set ProductInfo = .NET/1.26.0 (.NET Core 3.1.10; Linux 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021; X64)
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set ClientOptions = (null)
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [CreateFromConnectionString] Informational: InternalClient#10598606 HostName=home;DeviceId=opc;ModuleId=opcpublisher Mqtt_Tcp_Only
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: InternalClient#10598606 SetConnectionStatusChangesHandler ConnectionStatusChangesHandler#380433835
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: RetryDelegatingHandler#11958757 EnsureOpenedAsync Opening connection
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: ProtocolRoutingDelegatingHandler#20031746 ProtocolRoutingDelegatingHandler.OpenAsync Trying Mqtt_Tcp_Only
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: PipelineContext#53180767 Set ITransportSettings = MqttTransportSettings#30265903
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: (null) GetEventLoopGroup EventLoopGroup threads count was not set.
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: MqttTransportHandler#3957675 CreateChannelFactory Connecting to 172.18.0.3
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [GenerateToken] Informational: ModuleAuthenticationWithHsm#36936550 2021-02-23T22:12:16.7928596Z 2021-02-23T23:12:17.0000000Z
[22:12:16 INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module opc_opcpublisher reconnected due to Connection_Ok.
[22:12:16 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: MqttIotHubAdapter#14347911 SendMessageAsync id=0 qos=AtMostOnce topic=$iothub/twin/GET/?$rid=0ea1cc6c-d682-411a-9f2f-01d52a9ad381
[22:12:17 INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Initialize device twin for opc - opcpublisher
[22:12:17 INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Applying initial desired state.
[22:12:17 INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Reporting currently initial state.
[22:12:17 DBG Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Reporting controller state...
[22:12:17 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: MqttIotHubAdapter#14347911 SendMessageAsync id=0 qos=AtMostOnce topic=$iothub/twin/PATCH/properties/reported/?$rid=06c49081-fa9e-4649-a1ab-475fc760ef1d
[22:12:17 DBG Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Complete controller state reported (properties: ["IdentityToken"]).
[22:12:17 DBG Microsoft.Azure.Devices.Device.Client] [Info] Informational: MqttIotHubAdapter#14347911 SendMessageAsync id=0 qos=AtMostOnce topic=$iothub/twin/PATCH/properties/reported/?$rid=ca201da1-3cbc-4f51-9831-baed9da87273
[22:12:17 INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Module Host started.
[22:12:17 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Creating new worker...
[22:12:17 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] File /appdata/publishednodes.json has changed, reloading...
[22:12:17 DBG Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter] Reading published nodes file (00:00:00.0000003
[22:12:17 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter] Read 1 items from published nodes file in 00:00:00.0203134
[22:12:17 INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter] Converted items to jobs in 00:00:00.0323890
[22:12:17 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Starting worker 'StandalonePublisher_0'...
[22:12:17 DBG Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Sending heartbeat...
[22:12:17 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Worker StandalonePublisher_0: {}
[22:12:17 DBG Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Worker starting...
[22:12:17 DBG Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Try querying available job...
[22:12:17 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Worker: StandalonePublisher_0 processing job: Standalone_opc_opcpublisher, mode: Active
[22:12:32 ERR Root] Error during module execution - restarting!
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.IIoT.OpcUa.Protocol.IClientServicesConfig, Microsoft.Azure.IIoT.Module.IIdentity, Serilog.ILogger)' on type 'DefaultSessionManager'.
 ---> System.AggregateException: One or more errors occurred. (OPC UA configuration not valid)
 ---> Microsoft.Azure.IIoT.Exceptions.InvalidConfigurationException: OPC UA configuration not valid
 ---> Opc.Ua.ServiceResultException: Cannot access certificate private key. Subject=DC=home, O=device1, CN=opcpublisher
   at Microsoft.Azure.IIoT.Utils.Retry.DelayOrThrow(ILogger logger, Func`2 cont, Func`3 policy, Int32 maxRetry, Int32 k, Exception ex, CancellationToken ct) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Core\src\Utils\Retry.cs:line 725
   at Microsoft.Azure.IIoT.Utils.Retry.Do(ILogger logger, CancellationToken ct, Func`1 work, Func`2 cont, Func`3 policy, Int32 maxRetry) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Core\src\Utils\Retry.cs:line 80
   at Microsoft.Azure.IIoT.OpcUa.Protocol.OpcConfigEx.ToApplicationConfigurationAsync(IClientServicesConfig opcConfig, IIdentity identity, Boolean createSelfSignedCertIfNone, CertificateValidationEventHandler handler) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Runtime\Extensions\OpcConfigEx.cs:line 60
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.OpcUa.Protocol.OpcConfigEx.ToApplicationConfigurationAsync(IClientServicesConfig opcConfig, IIdentity identity, Boolean createSelfSignedCertIfNone, CertificateValidationEventHandler handler) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Runtime\Extensions\OpcConfigEx.cs:line 110
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager..ctor(IClientServicesConfig clientConfig, IIdentity identity, ILogger logger) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Services\DefaultSessionManager.cs:line 42
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.ModuleProcess.RunAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\ModuleProcess.cs:line 111
[22:12:32 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Stopping worker supervisor
[22:12:32 INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Stopping worker...
```

If I delete my certs and let the opcpublisher create them, it works fine as shown by the tree below.  My goal is to use specified certs with a date longer than one year. 

```
root@home:/iiotedgecerts# tree
.
├── own
│   ├── certs
│   │   └── opcpublisher [652D9F5BDD9FDA935DD3520F3EADD123DB6CF344].der
│   └── private
│       └── opcpublisher [652D9F5BDD9FDA935DD3520F3EADD123DB6CF344].pfx
└── trusted
    └── certs
        └── opcpublisher [652D9F5BDD9FDA935DD3520F3EADD123DB6CF344].der

5 directories, 3 files
```

**Comment by cristipogacean** [comment]
@ksaye, you can have a look on this one: https://github.com/Azure/Industrial-IoT/issues/757

**Comment by ksaye** [comment]
I have been basing most of my work on that issue.  Let me add the "-extfile cert.ext" piece and retest.  I would be surprised if the extension issue caused the ```Cannot access certificate private key``` error message.  Will update once I complete the testing.

**Comment by ksaye** [comment]
@cristipogacean, thanks for the comment.  The issue was based on missing extensions, and I have documented the process with the correct extensions here: https://kevinsaye.wordpress.com/2021/02/24/using-custom-x509-certificates-in-iot-edges-opc-publisher/.  Closing this ticket.
