### ISSUE TITLE
FileNotFoundException thrown for gatewayconfig.json file

### ISSUE THREAD

**Issue by JayeshThamke** [Azure/iot-edge-opc-publisher#40]
`System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not find file 'F:\gitHubRepo\opcPub\iot-edge-opc-publisher\src\GatewayApp.NetCore\bin\Debug\netcoreapp1.1\gatewayconfig.json'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at GatewayApp.NetCore.Program.Main(String[] args) in F:\gitHubRepo\opcPub\iot-edge-opc-publisher\src\GatewayApp.NetCore\Program.cs:line 33`

.NETCore app does not gatewayconfig.json file.

I wonder if it is because of the working directory has been changed in launchSettings.json.
` "workingDirectory": ".\\bin\\Debug\\netcoreapp1.1"`.

If I copy the file into above directory then application does not throw exception.

**Comment by barnstee** [comment]
publish the app.
