### ISSUE TITLE
TaskCanceledException when running the publisher

### ISSUE THREAD

**Issue by toddysm** [Azure/iot-edge-opc-publisher#88]
We are getting the below error when trying to start the OPC-UA Publisher container. Unfortunately with the information below we are not sure where to troubleshoot.

```
************************* Logging started at 11/05/2017 23:03:02
11/05/2017 23:03:02.241 Current directory is: /docker
11/05/2017 23:03:02.243 Log file is: /publisher/logs/cmc-iii-publisher.log.txt
11/05/2017 23:03:02.243 opcstacktracemask set to: 0x285 (645)
11/05/2017 23:03:02.311 There is no shopfloor domain configured.
11/05/2017 23:03:02.312 Publisher configured to not auto trust server certificates. When connecting to servers, you need to manually copy the rejected server certs to the trusted store to trust them.
11/05/2017 23:03:02.315 Starting server on endpoint opc.tcp://publisher-tsm001:62222/UA/Publisher ...
11/05/2017 23:03:04.171 MasterNodeManager.Startup - NodeManagers=3
11/05/2017 23:03:07.520 Server started.
11/05/2017 23:03:07.581 Publishing node configuration file path read from environment.
11/05/2017 23:03:07.581 Attempting to load nodes file from: /publisher/publishednodes.json
11/05/2017 23:03:09.887 Loaded 1 config file entry/entries.
11/05/2017 23:03:09.913 There are 1 nodes to publish.
11/05/2017 23:03:09.968 IoT Hub owner connection string not passed as argument.
11/05/2017 23:03:09.969 IoT Hub owner connection string read from environment.
11/05/2017 23:03:09.969 IoTHub device cert store type is: X509Store
11/05/2017 23:03:09.969 IoTHub device cert path is: My
11/05/2017 23:03:09.969 Attempting to register ourselves with IoT Hub using owner connection string: HostName=XXXXXXXXXXXXXXXXX;SharedAccessKeyName=iothubowner;SharedAccessKey=XXXXXXXXXXXXXXXXX
11/05/2017 23:03:11.686 Adding device 'publisher-tsm001' to IoTHub registry.
11/05/2017 23:03:12.679 Device connection string is: HostName=XXXXXXXXXXXXXXXXX;DeviceId=publisher-tsm001;SharedAccessKey=XXXXXXXXXXXXXXXXX
11/05/2017 23:03:12.683 Adding it to device cert store.
11/05/2017 23:03:17.977 Attempting to read device connection string from cert store using subject name: publisher-tsm001
11/05/2017 23:03:18.061 Create Publisher IoTHub client with device connection string: 'HostName=XXXXXXXXXXXXXXXXX.azure-devices.net;DeviceId=publisher-tsm001;SharedAccessKey=XXXXXXXXXXXXXXXXX' using 'Mqtt_WebSocket_Only' for communication.
11/05/2017 23:03:22.212 IoTHub messaging configured with a send interval of 10 sec and a message buffer size of 262144 bytes.
11/05/2017 23:03:22.224 Creating task process and batch monitored item data updates...
11/05/2017 23:03:23.352    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at OpcPublisher.Program.<SessionConnectorAsync>d__7.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 510
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpcPublisher.Program.<>c.<<MainAsync>b__6_34>d.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 422
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at OpcPublisher.Program.<MainAsync>d__6.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 443 TaskCanceledException 'A task was canceled.'

========================================
Id: Bad
Description: A task was canceled.
>>> A task was canceled.
---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
---    at OpcPublisher.Program.<SessionConnectorAsync>d__7.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 510
--- --- End of stack trace from previous location where exception was thrown ---
---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
---    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
---    at OpcPublisher.Program.<>c.<<MainAsync>b__6_34>d.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 422
--- --- End of stack trace from previous location where exception was thrown ---
---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
---    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
---    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
---    at OpcPublisher.Program.<MainAsync>d__6.MoveNext() in C:\Users\toddysm\OneDrive\Development\Projects\Remote\iot-edge-opc-publisher\src\Program.cs:line 443
========================================

11/05/2017 23:03:23.358 Publisher exiting... 
```

**Comment by toddysm** [comment]
After looking at the other issues it seems this one is related to https://github.com/Azure/iot-edge-opc-publisher/issues/86 - I was starting the container without the -it switches. However, I would like to vote up issue 86
